# Generated by Django 4.2.1 on 2023-05-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nhabitaciones', models.IntegerField()),
                ('nbanos', models.IntegerField()),
                ('nhuespuedes', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fotos', models.ImageField(upload_to='viajes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'alojamiento',
                'verbose_name_plural': 'alojamientos',
            },
        ),
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('vehiculo', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='viajes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'desplazamiento',
                'verbose_name_plural': 'desplazamientos',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='viajes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='viajes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='viajes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nHuespedes', models.FloatField()),
                ('salida', models.CharField(max_length=200)),
                ('llegada', models.CharField(max_length=200)),
                ('Alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.alojamiento')),
                ('DesplazamientoIda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_ida', to='principal.desplazamiento')),
                ('DesplazamientoVuelta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_vuelta', to='principal.desplazamiento')),
                ('Paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.paquete')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
            },
        ),
        migrations.AddField(
            model_name='desplazamiento',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destino'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destino'),
        ),
    ]
