# Generated by Django 4.2.1 on 2023-05-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desplazamiento',
            name='origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_origen', to='principal.destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desplazamiento',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_destino', to='principal.destino'),
        ),
    ]
