# Generated by Django 4.2.1 on 2023-05-31 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_customuser_foto_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='desplazamientoIda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_ida', to='principal.desplazamiento'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='desplazamientoVuelta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_vuelta', to='principal.desplazamiento'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='paquete',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='salida',
            field=models.DateField(),
        ),
    ]
