# Generated by Django 4.2.1 on 2023-05-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_desplazamiento_origen_alter_desplazamiento_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='Alojamiento',
            new_name='alojamiento',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='DesplazamientoIda',
            new_name='desplazamientoIda',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='DesplazamientoVuelta',
            new_name='desplazamientoVuelta',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Paquete',
            new_name='paquete',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
