# Generated by Django 4.2.1 on 2023-05-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.customuser'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
