# Generated by Django 4.2.1 on 2023-05-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_alojamiento_viaje_alojamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.destino'),
            preserve_default=False,
        ),
    ]
