# Generated by Django 4.2.1 on 2023-06-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rename_nhuespuedes_alojamiento_nhuespedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
        ),
    ]
