# Generated by Django 4.2.1 on 2023-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_viaje_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='pagado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
