# Generated by Django 4.2.1 on 2023-06-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_viaje_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precioTotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
