# Generated by Django 4.2.1 on 2023-06-09 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_viaje_preciototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='desplazamientoIda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_ida', to='principal.desplazamiento'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='desplazamientoVuelta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_vuelta', to='principal.desplazamiento'),
        ),
    ]
